---
AllCops:
  Exclude:
    - compile-extensions/**/*
    - vendor/**/*
    - cf_spec/unit/**/*
    - cf_spec/integration/**/*
Documentation:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 18
ParameterLists:
  Max: 9
Metrics/AbcSize:
  Max: 30
ClassLength:
  Max: 150
